pipeline 
{ 
        agent {
        docker {
             image 'cypress/base:18.16.0'
            // args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }


    parameters
    { 
        gitParameter branchFilter: 'origin/(.*)', defaultValue: 'develop', name: 'branch_name', type: 'PT_BRANCH' ,description: 'Please Choose Branch Name to Build '
    }
    
    environment {
        GIT_URL = 'git@github.com:spreezy-tech/spreezy-frontend.git'
        GIT_BRANCH = "${params.branch_name}"
        CREDENTIALS_ID = 'spreezy_credentials'
        JAVA_HOME = '/usr/lib/jvm/openjdk-17'
        PATH = "${JAVA_HOME}/bin:${PATH}"
        EMAIL_FROM = 'jenkins@spreezy.in'
        EMAIL_TO = 'spreezyindia@gmail.com'
        EMAIL_SUBJECT = 'Spreezy Frontend Project  Build -  '
        EMAIL_BODY = 'Spreezy Frontend Project Build Number  '
        SONAR_HOST_URL='http://103.105.111.78:6842'
        SONAR_TOKEN=credentials('sonarqube')
         SONAR_HOME = tool 'sonar-scanner'  
    }
    
     stages{
         
        stage('Clone Git Repo'){
            steps{
             git branch: env.GIT_BRANCH, credentialsId: env.CREDENTIALS_ID, url: env.GIT_URL
            }
        }
        

        stage('Nexus Setup And Install All Dependencies'){
            steps{
                
                withCredentials([file(credentialsId: 'nexus_npm_credentials', variable: 'npm_nexus_credentials')]) {
                 sh '''
                    npm config set fetch-timeout 600000
                    npm config set fetch-retries 2
                    npm install --userconfig ${npm_nexus_credentials} --registry https://nexus.spreezy.in/repository/npm-group/ --loglevel verbose
                '''                
                }
            }
        }
        

        
        // stage('Run Tests'){
        //     steps {
            
        //     sh 'npm start &'

        //     // Wait for Angular application to start
        //     sh 'npx wait-on http://localhost:4200'

        //     // Run Cypress tests
        //     sh 'NO_COLOR=1 npm run test'
        //     sh 'npm run test:coverage'


        //     sh 'pkill -f "npm start"'

        //     }
        // }
        stage('Run Tests') {
            steps {
                script {
                    def skip_test = true  // Set to 'true' to skip tests, 'false' to run them

                    sh 'npm start &'

                    // Wait for Angular application to start
                    sh 'npx wait-on http://localhost:4200'

                    if (!skip_test) {
                        sh 'NO_COLOR=1 npm run test'
                        sh 'npm run test:coverage'
                    } else {
                        echo 'Skipping Cypress tests as skip_test is set to true'
                    }

                    sh 'pkill -f "npm start"'
                }
            }
        }
    }
     
  post{
        always{
            // publishHTML(target: [allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'coverage/lcov-report', reportFiles: 'index.html', reportName: 'Code Coverage Report'])

            // slackSend channel: 'devops-jenkins-updates', message: "Please find status of pipeline here Status - ${currentBuild.currentResult}  ${env.JOB_NAME}   Build Number ${env.BUILD_NUMBER}  URL ${env.BUILD_URL}"   
            //clean workspace after every build
            cleanWs()
        }
    }

}

